apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go-deployment
  labels:
    app: testgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgo
  template:
    metadata:
      labels:
        app: testgo
    spec:
      containers:
      - name: testgo
        image: chakorn/testgo:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
